### ISSUE TITLE
Wireguard tools

### ISSUE THREAD

**Issue by samip5** [FossoresLP/vyatta-wireguard#4]
Does the package include wg-quick CLI helper?

I would love to use it to do quick interfaces.

**Comment by FossoresLP** [comment]
wg-quick is not included in the packages as it could possibly interfere with the vyatta configuration this package includes.
Since wg-quick is only a bash script you could however [download it](https://git.zx2c4.com/wireguard-tools/tree/src/wg-quick/linux.bash) yourself and try it. There is no guarantee that it won't break something however.
